openapi: 3.0.0
info:
  title: user-service api
  description: User Service Microservice API
components:
  securitySchemes:
#    ApiKeyAuth:        # arbitrary name for the security scheme
#      type: apiKey
#      in: header       # can be "header", "query" or "cookie"
#      name: token  # name of the header, query parameter or cookie
    cookieAuth:         # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: sid  # cookie name
      