package com.zhrenjie04.alex.user.domain;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Model class of t_privilege.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@ToString
@EqualsAndHashCode(of = {"privilegeId"})
public class Privilege {

	/** privilege_id. */
	private String privilegeId;

	/** privilege_name. */
	private String privilegeName;

	/** privilege_code. */
	private String privilegeCode;

	/** front_end_system. */
	private String frontEndSystem;

	/** simple_url. */
	private String simpleUrl;

	/** request_method. */
	private String requestMethod;

	/** is_menu. */
	private Boolean isMenu;

	/** parent_id. */
	private String parentId;

	/** id_path. */
	private String idPath;

	/** is_locked. */
	private Boolean isLocked;
	
	/** icon_class. */
	private String iconClass;
	
	/** icon_type. */
	private String iconType;

	/** ab. */
	private String ab;

	/** collapse. */
	private String collapse;

	/** sort_value. */
	private Double sortValue;

	private List<Privilege> children=new LinkedList<Privilege>();

	private Date createdTime;
	private String createrId;
	private String createrName;
	private Date lastModifiedTime;
	private String lastModifierId;
	private String lastModifierName;	
}
