package com.zhrenjie04.alex.manager.domain;

import java.util.List;

import com.zhrenjie04.alex.core.AbstractGenericEntity;

/**
 * Model class of t_org.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Com extends AbstractGenericEntity {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** org_id. */
	private String comId;

	/** org_name. */
	private String comName;

	/** org_code. */
	private String comCode;
	
	private List<ProjectDept> projectDepts;

	private List<Position> positions;
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((comId == null) ? 0 : comId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Com other = (Com) obj;
		if (comId == null) {
			if (other.comId != null) {
				return false;
			}
		} else if (!comId.equals(other.comId)) {
			return false;
		}
		return true;
	}

	@Override
	public String getPK() {
		return comId;
	}

	@Override
	public void setPK(String id) {
		this.comId=id;
	}

	public List<ProjectDept> getProjectDepts() {
		return projectDepts;
	}

	public void setProjectDepts(List<ProjectDept> projectDepts) {
		this.projectDepts = projectDepts;
	}

	public String getComId() {
		return comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	public String getComCode() {
		return comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getComName() {
		return comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}

	public List<Position> getPositions() {
		return positions;
	}

	public void setPositions(List<Position> positions) {
		this.positions = positions;
	}

}
