package com.zhrenjie04.alex.manager.domain;

import java.util.LinkedList;
import java.util.List;

import com.zhrenjie04.alex.core.AbstractGenericEntity;

/**
 * Model class of t_org.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Org extends AbstractGenericEntity {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** org_id. */
	private String orgId;

	/** org_name. */
	private String orgName;

	/** org_code. */
	private String orgCode;

	/** org_code. */
	private String orgType;

	/** office_location. */
	private String officeLocation;

	/** office_postcode. */
	private String officePostcode;

	/** office_tel. */
	private String officeTel;

	/** office_fax. */
	private String officeFax;

	/** office_contact. */
	private String officeContact;

	/** parent_id. */
	private String parentId;

	/** id_path. */
	private String idPath;

	/** is_locked. */
	private Boolean isLocked;

	/** com_id. */
	private String comId;

	/** group_id. */
	private String groupId;

	private List<Org> children=new LinkedList<Org>();
	
	public String getOrgId() {
		return orgId;
	}

	public void setOrgId(String orgId) {
		this.orgId = orgId;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getOfficeLocation() {
		return officeLocation;
	}

	public void setOfficeLocation(String officeLocation) {
		this.officeLocation = officeLocation;
	}

	public String getOfficePostcode() {
		return officePostcode;
	}

	public void setOfficePostcode(String officePostcode) {
		this.officePostcode = officePostcode;
	}

	public String getOfficeTel() {
		return officeTel;
	}

	public void setOfficeTel(String officeTel) {
		this.officeTel = officeTel;
	}

	public String getOfficeFax() {
		return officeFax;
	}

	public void setOfficeFax(String officeFax) {
		this.officeFax = officeFax;
	}

	public String getOfficeContact() {
		return officeContact;
	}

	public void setOfficeContact(String officeContact) {
		this.officeContact = officeContact;
	}

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getIdPath() {
		return idPath;
	}

	public void setIdPath(String idPath) {
		this.idPath = idPath;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((orgId == null) ? 0 : orgId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Org other = (Org) obj;
		if (orgId == null) {
			if (other.orgId != null) {
				return false;
			}
		} else if (!orgId.equals(other.orgId)) {
			return false;
		}
		return true;
	}

	@Override
	public String getPK() {
		return orgId;
	}

	@Override
	public void setPK(String id) {
		this.orgId=id;
	}

	public List<Org> getChildren() {
		return children;
	}

	public void setChildren(List<Org> children) {
		this.children = children;
	}

	public Boolean getIsLocked() {
		return isLocked;
	}

	public void setIsLocked(Boolean isLocked) {
		this.isLocked = isLocked;
	}

	public String getGroupId() {
		return groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getOrgType() {
		return orgType;
	}

	public void setOrgType(String orgType) {
		this.orgType = orgType;
	}

	public String getComId() {
		return comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

}
