package com.zhrenjie04.alex.manager.domain;

import javax.validation.constraints.NotEmpty;

import com.zhrenjie04.alex.core.AbstractGenericEntity;

/**
 * Model class of t_position.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Position extends AbstractGenericEntity {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** position_id. */
	private String positionId;

	/** position_name. */
	@NotEmpty(message = "职位名称不能为空")
	private String positionName;

	/** position_code. */
	@NotEmpty(message = "职位代码不能为空")
	private String positionCode;

	/** group_id. */
	private String groupId;

	/** is_locked. */
	private Boolean isLocked;

	public String getPositionId() {
		return positionId;
	}

	public void setPositionId(String positionId) {
		this.positionId = positionId;
	}

	public String getPositionName() {
		return positionName;
	}

	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	public String getPositionCode() {
		return positionCode;
	}

	public void setPositionCode(String positionCode) {
		this.positionCode = positionCode;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((positionId == null) ? 0 : positionId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Position other = (Position) obj;
		if (positionId == null) {
			if (other.positionId != null) {
				return false;
			}
		} else if (!positionId.equals(other.positionId)) {
			return false;
		}
		return true;
	}

	@Override
	public String getPK() {
		return positionId;
	}

	@Override
	public void setPK(String id) {
		this.positionId = id;
	}

	public String getGroupId() {
		return groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public Boolean getIsLocked() {
		return isLocked;
	}

	public void setIsLocked(Boolean isLocked) {
		this.isLocked = isLocked;
	}

}
