package com.zhrenjie04.alex.manager.domain;

import com.zhrenjie04.alex.core.AbstractGenericEntity;

/**
 * Model class of t_project_dept.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProjectDept extends AbstractGenericEntity {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** project_dept_id. */
	private String projectDeptId;

	/** project_dept_name. */
	private String projectDeptName;

	/** project_code. */
	private String projectDeptCode;
	
	private String comId;
	
	private String groupId;

	/** office_location. */
	private String officeLocation;

	/** office_postcode. */
	private String officePostcode;

	/** office_tel. */
	private String officeTel;

	/** office_fax. */
	private String officeFax;

	/** office_contact. */
	private String officeContact;

	/** main_org_id. */
	private String mainOrgId;

	/** main_org_name. */
	private String mainOrgName;

	
	public String getProjectDeptId() {
		return projectDeptId;
	}

	public void setProjectDeptId(String projectDeptId) {
		this.projectDeptId = projectDeptId;
	}

	public String getProjectDeptName() {
		return projectDeptName;
	}

	public void setProjectDeptName(String projectDeptName) {
		this.projectDeptName = projectDeptName;
	}

	public String getProjectDeptCode() {
		return projectDeptCode;
	}

	public void setProjectDeptCode(String projectCode) {
		this.projectDeptCode = projectCode;
	}

	public String getOfficeLocation() {
		return officeLocation;
	}

	public void setOfficeLocation(String officeLocation) {
		this.officeLocation = officeLocation;
	}

	public String getOfficePostcode() {
		return officePostcode;
	}

	public void setOfficePostcode(String officePostcode) {
		this.officePostcode = officePostcode;
	}

	public String getOfficeTel() {
		return officeTel;
	}

	public void setOfficeTel(String officeTel) {
		this.officeTel = officeTel;
	}

	public String getOfficeFax() {
		return officeFax;
	}

	public void setOfficeFax(String officeFax) {
		this.officeFax = officeFax;
	}

	public String getOfficeContact() {
		return officeContact;
	}

	public void setOfficeContact(String officeContact) {
		this.officeContact = officeContact;
	}

	public String getMainOrgId() {
		return mainOrgId;
	}

	public void setMainOrgId(String mainOrgId) {
		this.mainOrgId = mainOrgId;
	}

	public String getMainOrgName() {
		return mainOrgName;
	}

	public void setMainOrgName(String mainOrgName) {
		this.mainOrgName = mainOrgName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((projectDeptId == null) ? 0 : projectDeptId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProjectDept other = (ProjectDept) obj;
		if (projectDeptId == null) {
			if (other.projectDeptId != null) {
				return false;
			}
		} else if (!projectDeptId.equals(other.projectDeptId)) {
			return false;
		}
		return true;
	}

	@Override
	public String getPK() {
		return projectDeptId;
	}

	@Override
	public void setPK(String id) {
		this.projectDeptId=id;
	}

	public String getComId() {
		return comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	public String getGroupId() {
		return groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

}
